spring.application.name=backend

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.url=jdbc:postgresql://prod-host:5432/store
spring.datasource.username=prod_user
spring.datasource.password=strongpassword

server.port=8080